### ISSUE TITLE
Problems running large PCAs

### ISSUE THREAD

**Issue by alimanfoo** [malariagen/malariagen-data-python#601]
I'm having problems running a PCA across the whole of the Ag3 resource. I'm running on a dask cluster with ~100 workers, all goes fine through the initial allele counts stage, but then the cluster grinds to a halt I think during the computation of the biallelic diplotypes.

I eventually got an error message about jobs being retried and failing multiple times, and have an associated stack trace for one of the workers where the job failed, here is an extract:

```
File "/opt/coiled/env/lib/python3.12/site-packages/allel/abc.py", line 40, in __getattr__
return getattr(self.values, item)
^^^^^^^^^^^
File "/opt/coiled/env/lib/python3.12/site-packages/allel/abc.py", line 26, in values
return self._values
^^^^^^^^^^^^
File "/opt/coiled/env/lib/python3.12/site-packages/allel/abc.py", line 40, in __getattr__
return getattr(self.values, item)
^^^^^^^^^^^
File "/opt/coiled/env/lib/python3.12/site-packages/allel/abc.py", line 26, in values
return self._values
^^^^^^^^^^^^
File "/opt/coiled/env/lib/python3.12/site-packages/allel/abc.py", line 40, in __getattr__
return getattr(self.values, item)
^^^^^^^^^^^
File "/opt/coiled/env/lib/python3.12/site-packages/allel/abc.py", line 26, in values
return self._values
^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded
distributed.worker - INFO - Stopping worker at tls://10.0.0.70:40125. Reason: check-worker-ttl-1726482783.8158462
distributed.worker - ERROR - failed during get data with tls://10.0.0.70:40125 -> tls://10.0.0.73:44005
```

Full trace: [gsu-vector-team-ca83e1d6-worker-30873129b3-instance.txt](https://github.com/user-attachments/files/17013444/gsu-vector-team-ca83e1d6-worker-30873129b3-instance.txt)

My guess is that there is a recursion error triggered when objects are being pickled and unpickled for transfer between dask workers. This is associated with scikit-allel array wrapper objects, which could be e.g. an instance of `AlleleCountsArray` or `GenotypeArray`. Confirming that this does occur, this code:

```python
import allel
import pickle

ac = allel.AlleleCountsArray(
    [[0, 10], [5, 5]]
)
pickle.loads(pickle.dumps(ac))
```

...gerates this trace:

```
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
Cell In[3], line 7
      2 import pickle
      4 ac = allel.AlleleCountsArray(
      5     [[0, 10], [5, 5]]
      6 )
----> 7 pickle.loads(pickle.dumps(ac))

File /home/conda/global/ed168cff47e4d286b98549fb3c35a1f734f57225dd106a89340e6bb53ac0ae59-20240915-075204-087108-72-mgenv-6.0.0/lib/python3.12/site-packages/allel/abc.py:40, in ArrayWrapper.__getattr__(self, item)
     36 if item in {'__array_struct__', '__array_interface__'}:
     37     # don't pass these through because we want to use __array__ to control numpy
     38     # behaviour
     39     raise AttributeError
---> 40 return getattr(self.values, item)

File /home/conda/global/ed168cff47e4d286b98549fb3c35a1f734f57225dd106a89340e6bb53ac0ae59-20240915-075204-087108-72-mgenv-6.0.0/lib/python3.12/site-packages/allel/abc.py:26, in ArrayWrapper.values(self)
     17 @property
     18 def values(self):
     19     """The underlying array of values.
     20 
     21     Returns
   (...)
     24 
     25     """
---> 26     return self._values

File /home/conda/global/ed168cff47e4d286b98549fb3c35a1f734f57225dd106a89340e6bb53ac0ae59-20240915-075204-087108-72-mgenv-6.0.0/lib/python3.12/site-packages/allel/abc.py:40, in ArrayWrapper.__getattr__(self, item)
     36 if item in {'__array_struct__', '__array_interface__'}:
     37     # don't pass these through because we want to use __array__ to control numpy
     38     # behaviour
     39     raise AttributeError
---> 40 return getattr(self.values, item)

File /home/conda/global/ed168cff47e4d286b98549fb3c35a1f734f57225dd106a89340e6bb53ac0ae59-20240915-075204-087108-72-mgenv-6.0.0/lib/python3.12/site-packages/allel/abc.py:26, in ArrayWrapper.values(self)
     17 @property
     18 def values(self):
     19     """The underlying array of values.
     20 
     21     Returns
   (...)
     24 
     25     """
---> 26     return self._values

    [... skipping similar frames: ArrayWrapper.__getattr__ at line 40 (1486 times), ArrayWrapper.values at line 26 (1485 times)]

File /home/conda/global/ed168cff47e4d286b98549fb3c35a1f734f57225dd106a89340e6bb53ac0ae59-20240915-075204-087108-72-mgenv-6.0.0/lib/python3.12/site-packages/allel/abc.py:26, in ArrayWrapper.values(self)
     17 @property
     18 def values(self):
     19     """The underlying array of values.
     20 
     21     Returns
   (...)
     24 
     25     """
---> 26     return self._values

File /home/conda/global/ed168cff47e4d286b98549fb3c35a1f734f57225dd106a89340e6bb53ac0ae59-20240915-075204-087108-72-mgenv-6.0.0/lib/python3.12/site-packages/allel/abc.py:40, in ArrayWrapper.__getattr__(self, item)
     36 if item in {'__array_struct__', '__array_interface__'}:
     37     # don't pass these through because we want to use __array__ to control numpy
     38     # behaviour
     39     raise AttributeError
---> 40 return getattr(self.values, item)

RecursionError: maximum recursion depth exceeded
```

Raising here as it prevents large PCAs from being run, but the fix probably needs to happen upstream in scikit-allel.

**Comment by alimanfoo** [comment]
Unfortunately this is still not resolved. I've fixed the upstream issue https://github.com/cggh/scikit-allel/issues/424 but in doing so have created a new bug https://github.com/cggh/scikit-allel/issues/426. Working on a fix now.

**Comment by alimanfoo** [comment]
After upgrading to scikit-allel v1.3.13 I have managed to run a PCA of all Ag3 samples up to and including Ag3.13 (21,666) almost all the way to the end. All of the data preparation steps complete. But then the SVD calculation fails with:

```
svd ValueError: Indexing a matrix of 2352060960 elements would incur an in integer overflow in LAPACK.
```

It looks like the underlying SVD implementation uses 32-bit integers and so cannot handle input data with more than 2,147,483,647 elements. We will hit this with ~20,000 samples and ~100,000 SNPs. This doesn't look easy to resolve, so the workaround will have to be run with less SNPs.

**Comment by alimanfoo** [comment]
I've managed to get a PCA of all Ag to run, so will close this one for now. Have raised a follow-up issue #607 to capture possible further improvements in making it easier to run big PCAs.
